#!/bin/sh
# NOTE: this requires the keystore to be at ~/unilinktix.keystore
rm platforms/android/build/outputs/apk/android-release.apk
cordova build android --release
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/unilinktix.keystore platforms/android/build/outputs/apk/android-release-unsigned.apk unilinktix
zipalign -v 4 platforms/android/build/outputs/apk/android-release-unsigned.apk platforms/android/build/outputs/apk/android-release.apk
echo "APK ready for upload: platforms/android/build/outputs/apk/android-release.apk"